### ISSUE TITLE
убрать лишние элементы из таблицы ордеров (убрать руль оставить газ)

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#483]
# Problem
на странице где главное действие начать свап (нажать плей) сверху форма которая путает всех. все жмут create order 

# Task

выпилить нафиг выбор направления, а кнопку добавления ордера сделать маленькой и скромной, так как она нужна только для профи. 90% людей будут брать с рынка заявки.
![](https://i.imgur.com/6k3fhDC.png)

# Purpose
улучшение юзабилити, так как из центра управления космолетом с кучей вариантов движения интерфейс превращается в дорогу где только надо жать на газ

# Area
на конечной странице с ордербуком

# Estimate time of implementation
1 час

# Additional data

**Comment by noxonsu** [comment]
не все а то на какое человек перещел. тоесть если он зашел на https://swap.online/btc-eos то показывать направление на покупку btc за eos без возможности поменять направление. если ему надо будет он пойдет снова на галвную и зайдет по новой

**Comment by noxonsu** [comment]
все еще вижу форму выбора направления, ее нужно убрать

**Comment by noxonsu** [comment]
чтоб при нажатии на ексчендж в шапке появлялась форма эта

**Comment by xahon** [comment]
![image](https://user-images.githubusercontent.com/18731681/46188753-69753100-c32e-11e8-8af1-a9ccc046b109.png)

----> `SEARCH`

![image](https://user-images.githubusercontent.com/18731681/46188777-890c5980-c32e-11e8-8ba7-d9435c1fb311.png)

**Comment by noxonsu** [comment]
Noxon, [28.09.18 17:44]
посмотрел скрины в первом убери синий подзаголово там про биткоин

Noxon, [28.09.18 17:44]
и форму всю центруй наверно, кнопка серч ближе к выбору направления

Noxon, [28.09.18 17:45]
search поменять show orders

Noxon, [28.09.18 17:46]
снизу добавь в айфреме what is atomic swap? вставь видео с ютуба https://www.youtube.com/watch?v=Jhrb7xOT_7s

**Comment by xahon** [comment]
- [x] посмотрел скрины в первом убери синий подзаголово там про биткоин

- [ ] и форму всю центруй наверно, кнопка серч ближе к выбору направления

- [ ] search поменять show orders

- [ ] снизу добавь в айфреме what is atomic swap? вставь видео с ютуба https://www.youtube.com/watch?v=Jhrb7xOT_7s

**Comment by xahon** [comment]
@noxonsu по второму так? 
![image](https://user-images.githubusercontent.com/18731681/46197581-9a189300-c34d-11e8-8784-32da0ea899b6.png)

Если центрировать, то элементы могут прыгать в разные стороны

**Comment by xahon** [comment]
@noxonsu по четвертому это в `/exchange`?

**Comment by xahon** [comment]
![image](https://user-images.githubusercontent.com/18731681/46198537-101df980-c350-11e8-8bf8-31c8fd14bd3e.png)

**Comment by caffeinum** [comment]
> посмотрел скрины в первом убери синий подзаголово там про биткоин

я бы его оставил, просто вместо SWAP - BTC написать CRYPTO

**Comment by nikdementev** [comment]
Идея с видео мне очень не нравится, для подобного надо сделать FAQ на сайте
и показывать его перед началом работы с сайтом а не заниматься подобным вещами
@noxonsu

**Comment by caffeinum** [comment]
@nikdementev не согласен, потому что в FAQ никто заходить не будет. Лучше видео залить не в ютуб и сделать нормальный плеер

**Comment by nikdementev** [comment]
Сделать плашки модальные окна перед заходом на сайт, где будет все рассказываться а в последней просится сохранить приватники)))

**Comment by noxonsu** [comment]
видео центровать в лево, справа от видео разместить топ вопросов из FAQ подтяни json с вики (поросить Иона сделать json https://wiki.swap.online/faq) ну или просто тупо скопипастни оттуда текст

**Comment by BootWP** [comment]
Вопросы в json формате https://wiki.swap.online/wp-json/swap/faq/
